enum PermissionsEnum {
  ROLES_VIEW = 'ROLES_VIEW',
  ROLES_ADD = 'ROLES_ADD',
  ROLES_EDIT = 'ROLES_EDIT',
  ROLES_DELETE = 'ROLES_DELETE',
  ROLES_PERMISSIONS_VIEW = 'ROLES_PERMISSIONS_VIEW',
  ROLES_PERMISSIONS_EDIT = 'ROLES_PERMISSIONS_EDIT',

  USERS_VIEW = 'USERS_VIEW',
  USERS_LIST = 'USERS_LIST',
  USERS_ADD = 'USERS_ADD',
  USERS_EDIT = 'USERS_EDIT',
  USERS_DELETE = 'USERS_DELETE',
  USERS_PERMISSIONS = 'USERS_PERMISSIONS',
  USERS_PERMISSIONS_VIEW = 'USERS_PERMISSIONS_VIEW',
  USERS_PERMISSIONS_EDIT = 'USERS_PERMISSIONS_EDIT',

}

export default PermissionsEnum;
